create database db_tertiary;

create table category
(
    id   integer generated by default as identity (minvalue 0 maxvalue 999)
        primary key,
    name varchar(50)
);

alter table category
    owner to root;
